
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LOG660.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class ADRESSE
{

    public decimal IDADRESSE { get; set; }

    public string NOCIVIC { get; set; }

    public string RUE { get; set; }

    public string APP { get; set; }

    public string VILLE { get; set; }

    public string ZIP { get; set; }

    public string PROVINCE { get; set; }

    public string PAYS { get; set; }

    public decimal IDUSAGER { get; set; }



    public virtual USAGER USAGER { get; set; }

}

}
