
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LOG660.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class DIMENSIONTEMP
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DIMENSIONTEMP()
    {

        this.FAITLOCATIONFILMCLIENTINSTANTs = new HashSet<FAITLOCATIONFILMCLIENTINSTANT>();

    }


    public decimal IDTEMPS { get; set; }

    public System.DateTime DATECOMPLET { get; set; }

    public decimal HEURE { get; set; }

    public string JOUR { get; set; }

    public string MOIS { get; set; }

    public decimal ANNE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAITLOCATIONFILMCLIENTINSTANT> FAITLOCATIONFILMCLIENTINSTANTs { get; set; }

}

}
