
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LOG660.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class DIMENSIONFILM
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DIMENSIONFILM()
    {

        this.FAITLOCATIONFILMCLIENTINSTANTs = new HashSet<FAITLOCATIONFILMCLIENTINSTANT>();

    }


    public decimal IDFILM { get; set; }

    public string TITRE { get; set; }

    public decimal ANNEESORTIE { get; set; }

    public string ORIGINE { get; set; }

    public string ISCOMEDY { get; set; }

    public string ISFAMILY { get; set; }

    public string ISMYSTERY { get; set; }

    public string ISANIMATION { get; set; }

    public string ISSCIFY { get; set; }

    public string ISBIOGRAPHIE { get; set; }

    public string ISMUSICAL { get; set; }

    public string ISTHRILLER { get; set; }

    public string ISFILMNOIR { get; set; }

    public string ISADVENTURE { get; set; }

    public string ISROMANCE { get; set; }

    public string ISSPORT { get; set; }

    public string ISDRAMA { get; set; }

    public string ISHORROR { get; set; }

    public string ISWESTERN { get; set; }

    public string ISACTION { get; set; }

    public string ISFANTASY { get; set; }

    public string ISWAR { get; set; }

    public string ISDOCUMENTARY { get; set; }

    public string ISCRIME { get; set; }

    public string ISHISTORY { get; set; }

    public string ISMUSIC { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAITLOCATIONFILMCLIENTINSTANT> FAITLOCATIONFILMCLIENTINSTANTs { get; set; }

}

}
