//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILM()
        {
            this.ACTEURFILMs = new HashSet<ACTEURFILM>();
            this.EXEMPLAIREs = new HashSet<EXEMPLAIRE>();
            this.GENREs = new HashSet<GENRE>();
            this.PAYSPRODUCTIONs = new HashSet<PAYSPRODUCTION>();
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public decimal IDFILM { get; set; }
        public string TITRE { get; set; }
        public Nullable<decimal> ANNEESORTIE { get; set; }
        public decimal IDREALISATEUR { get; set; }
        public string LANGUEORIGINAL { get; set; }
        public Nullable<decimal> DUREE { get; set; }
        public decimal IDRESUME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTEURFILM> ACTEURFILMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXEMPLAIRE> EXEMPLAIREs { get; set; }
        public virtual PERSONNE PERSONNE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENRE> GENREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYSPRODUCTION> PAYSPRODUCTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
    }
}
