
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LOG660.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class MA_VUE_CORRELATIONS
{

    public Nullable<decimal> CORRELATION { get; set; }

    public decimal FILM1 { get; set; }

    public decimal FILM2 { get; set; }

}

}
