//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIOGRAPHIE
    {
        public BIOGRAPHIE()
        {
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public decimal IDBIOGRAPHIE { get; set; }
        public string BIOGRAPHIE1 { get; set; }
    
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
    }
}
