//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXEMPLAIRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXEMPLAIRE()
        {
            this.LIGNELOCATIONs = new HashSet<LIGNELOCATION>();
        }
    
        public decimal IDEXEMPLAIRE { get; set; }
        public decimal IDFILM { get; set; }
    
        public virtual FILM FILM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNELOCATION> LIGNELOCATIONs { get; set; }
    }
}
