//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNELOCATION
    {
        public LIGNELOCATION()
        {
            this.LOCATIONs = new HashSet<LOCATION>();
        }
    
        public decimal IDLIGNELOCATION { get; set; }
        public decimal IDEXEMPLAIRE { get; set; }
        public System.DateTime DATELOCATION { get; set; }
        public System.DateTime DATERETOUR { get; set; }
    
        public virtual EXEMPLAIRE EXEMPLAIRE { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
    }
}
