//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYSPRODUCTION
    {
        public PAYSPRODUCTION()
        {
            this.FILMs = new HashSet<FILM>();
        }
    
        public decimal IDPAYS { get; set; }
        public string NOM { get; set; }
    
        public virtual ICollection<FILM> FILMs { get; set; }
    }
}
