//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOG660.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class USAGER
    {
        public USAGER()
        {
            this.ADRESSEs = new HashSet<ADRESSE>();
            this.LOCATIONs = new HashSet<LOCATION>();
        }
    
        public decimal IDUSAGER { get; set; }
        public string NOM { get; set; }
        public string COURRIEL { get; set; }
        public System.DateTime DATENAISSANCE { get; set; }
        public string TELEPHONE { get; set; }
        public string MOTPASSE { get; set; }
    
        public virtual ICollection<ADRESSE> ADRESSEs { get; set; }
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
    }
}
